ename: Install
on: 
  -  [push]
  -  workflow_dispatch
jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
             apt-get update && apt-get install -y ca-certificates fakeroot build-essential python3 cmake pkg-config zip
             cd packaging
             apt install -y $(./chkdeps.sh -l | cut -d':' -f2 | tr '\n' ' ')
             gem install sass
             ./buildall.sh
             zip -r xptc-debian.zip xptc
             upload=$(realpath xptc-debian.zip)
             echo "FILES=${upload}" >> $GITHUB_ENV
          
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: latest build
          body: "This release includes the latest build for xfce-winxp-tc ."
          files: |
            ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             


            
