name: Install
on: 
   workflow_dispatch:
jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
           
              sudo apt-get update 
              sudo apt-get install -y ca-certificates fakeroot build-essential python3 cmake pkg-config zip
             cd packaging
             sudo apt install -y $(./chkdeps.sh -l | cut -d':' -f2 | tr '\n' ' ')
             sudo gem install sass
             ./buildall.sh
             zip -r xptc-debian.zip xptc
             upload=$(realpath xptc-debian.zip)
             echo "FILES=${upload}" >> $GITHUB_ENV
          
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-ubuntu
          name: latest build
          body: "This release includes the latest build for xfce-winxp-tc ."
          files: |
            ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             


            
